# Generated by Django 2.2.11 on 2020-03-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publishd_date',
            new_name='published_date',
        ),
    ]
